import type { BuildingName } from '../types/village';

export const buildingNameFa: Record<BuildingName, string> = {
	Woodcutter: 'هیزم‌شکن',
	Clay_Pit: 'گودال رس',
	Iron_Mine: 'معدن آهن',
	Cropland: 'مزرعه گندم',
	Sawmill: 'چوب‌بری',
	Brickyard: 'آجرپزی',
	Iron_Foundry: 'ذوب‌آهن',
	Grain_Mill: 'آسیاب',
	Bakery: 'نانوایی',
	Warehouse: 'انبار',
	Granary: 'انبار غلات',
	Blacksmith: 'آهنگری',
	Armoury: 'زره‌سازی',
	Tournament_Square: 'میدان مسابقات',
	Main_Building: 'ساختمان اصلی',
	Camp: 'اردوگاه',
	Marketplace: 'بازار',
	Embassy: 'سفارتخانه',
	Barracks: 'سربازخانه',
	Stable: 'اصطبل',
	Workshop: 'کارگاه',
	Academy: 'آکادمی',
	Cranny: 'مخفیگاه',
	Town_Hall: 'تالار شهر',
	Residence: 'اقامتگاه',
	Palace: 'قصر',
	Treasury: 'خزانه',
	Trade_Office: 'دفتر تجارت',
	Great_Barracks: 'سربازخانه بزرگ',
	Great_Stable: 'اصطبل بزرگ',
	Stonemason_Lodge: 'سنگ‌تراشی',
	Brewery: 'آبجوسازی',
	Trapper: 'تله‌گذار',
	Hero_Mansion: 'عمارت قهرمان',
	Great_Warehouse: 'انبار بزرگ',
	Great_Granary: 'انبار غلات بزرگ',
	World_Wonder: 'شگفتی جهان',
	Horse_Drinking_Trough: 'آبشخور اسب',
	Wall: 'دیوار',
};

export const BuildingList: BuildingName[] = [
	'Main_Building',
	'Warehouse',
	'Granary',
	'Wall',
	'Camp',
	'Embassy',
	'Barracks',
	'Marketplace',
	'Hero_Mansion',
	'Academy',
	'Palace',
	'Blacksmith',
	'Treasury',
	'Stable',
	'Town_Hall',
	'Workshop',
	'Tournament_Square',
	'Grain_Mill',
	'Iron_Foundry',
	'Sawmill',
	'Brickyard',
	'Bakery',
];

export const BuildingAddress: Partial<Record<BuildingName, number>> = {
	Town_Hall: 19,
	Warehouse: 20,
	Granary: 21,
	Hero_Mansion: 22,
	Sawmill: 23,
	Embassy: 24,
	Bakery: 25,
	Main_Building: 26,
	Workshop: 27,
	Academy: 28,
	Stable: 29,
	Tournament_Square: 30,
	Treasury: 31,
	Palace: 32,
	Blacksmith: 33,
	Brickyard: 34,
	Barracks: 35,
	Iron_Foundry: 36,
	Marketplace: 37,
	Grain_Mill: 38,
	Camp: 39,
	Wall: 40,
};

export const villageId: Record<BuildingName, number> = {
	Woodcutter: 1,
	Clay_Pit: 2,
	Iron_Mine: 3,
	Cropland: 4,
	Sawmill: 5,
	Brickyard: 6,
	Iron_Foundry: 7,
	Grain_Mill: 8,
	Bakery: 9,
	Warehouse: 10,
	Granary: 11,
	Blacksmith: 12,
	Armoury: 13,
	Tournament_Square: 14,
	Main_Building: 15,
	Camp: 16,
	Marketplace: 17,
	Embassy: 18,
	Barracks: 19,
	Stable: 20,
	Workshop: 21,
	Academy: 22,
	Cranny: 23,
	Town_Hall: 24,
	Residence: 25,
	Palace: 26,
	Treasury: 27,
	Trade_Office: 28,
	Great_Barracks: 29,
	Great_Stable: 30,
	Stonemason_Lodge: 32,
	Brewery: 33,
	Trapper: 36,
	Hero_Mansion: 37,
	Great_Warehouse: 38,
	Great_Granary: 39,
	World_Wonder: 41,
	Horse_Drinking_Trough: 41,
	Wall: -1,
};

export const buildingMap = Object.fromEntries(
	Object.entries(villageId).map(([building, id]) => [id, building]),
) as Record<number, BuildingName>;

export const max5Levels: BuildingName[] = [
	'Bakery',
	'Grain_Mill',
	'Iron_Foundry',
	'Brickyard',
	'Sawmill',
];

export const troopMap = {
	uhero: 'hero',
	u1: 'legionnaire',
	u2: 'praetorian',
	u3: 'imperian',
	u11: 'clubswinger',
	u12: 'spearman',
	u13: 'axeman',
} as const;
