const now = Date.now();

// TODO: replace mock data with a real-time feed (websocket or polling) from the
// automation engine's movements API once it is available.
const movements = reactive<Movement[]>([
	{
		id: 'mv1',
		group: 'outgoing',
		type: 'attack',
		sourceVillage: 'Northreach',
		destinationVillage: 'Dustholm',
		coordinates: '(33|-11)',
		tribe: 'teutons',
		hasHero: true,
		departureTime: '18:40',
		arrivalTime: '19:22',
		arrivalTimestamp: now + 1000 * 60 * 26,
		durationSeconds: 2520,
		elapsedSeconds: 950,
		status: 'traveling',
		distance: 7.1,
		attackTemplate: 'Full Attack',
		notes: 'Clearing defense before farming rotation.',
		troops: [
			{ troopName: 'Clubswinger', quantity: 180 },
			{ troopName: 'Paladin', quantity: 30 },
			{ troopName: 'Ram', quantity: 6 },
		],
		heroInfo: 'Hero riding with the main force.',
	},
	{
		id: 'mv2',
		group: 'outgoing',
		type: 'raid',
		sourceVillage: 'Northreach',
		destinationVillage: 'Rivermouth',
		coordinates: '(28|-9)',
		tribe: 'teutons',
		hasHero: false,
		departureTime: '18:50',
		arrivalTime: '19:04',
		arrivalTimestamp: now + 1000 * 60 * 8,
		durationSeconds: 840,
		elapsedSeconds: 360,
		status: 'traveling',
		distance: 4.2,
		attackTemplate: 'Mini Farm',
		troops: [{ troopName: 'Clubswinger', quantity: 20 }],
	},
	{
		id: 'mv3',
		group: 'outgoing',
		type: 'scout',
		sourceVillage: 'Millbrook',
		destinationVillage: 'Fenwick',
		coordinates: '(30|-13)',
		tribe: 'teutons',
		hasHero: false,
		departureTime: '18:58',
		arrivalTime: '19:10',
		arrivalTimestamp: now + 1000 * 60 * 14,
		durationSeconds: 720,
		elapsedSeconds: 100,
		status: 'preparing',
		distance: 6.4,
		troops: [{ troopName: 'Scout', quantity: 5 }],
	},
	{
		id: 'mv4',
		group: 'incoming',
		type: 'reinforcement-received',
		sourceVillage: 'Millbrook',
		destinationVillage: 'Northreach',
		coordinates: '(24|-12)',
		tribe: 'teutons',
		hasHero: false,
		departureTime: '18:20',
		arrivalTime: '19:00',
		arrivalTimestamp: now + 1000 * 60 * 4,
		durationSeconds: 2400,
		elapsedSeconds: 2160,
		status: 'arriving',
		distance: 5.0,
		troops: [{ troopName: 'Spearman', quantity: 60 }],
		notes: 'Defensive reinforcement from Millbrook.',
	},
	{
		id: 'mv5',
		group: 'returning',
		type: 'reinforcement-sent',
		sourceVillage: 'Ashford',
		destinationVillage: 'Northreach',
		coordinates: '(18|-27)',
		tribe: 'teutons',
		hasHero: false,
		departureTime: '17:10',
		arrivalTime: '19:40',
		arrivalTimestamp: now + 1000 * 60 * 45,
		durationSeconds: 9000,
		elapsedSeconds: 5400,
		status: 'returning',
		distance: 11.3,
		troops: [{ troopName: 'Spearman', quantity: 20 }],
	},
	{
		id: 'mv6',
		group: 'returning',
		type: 'raid',
		sourceVillage: 'Northreach',
		destinationVillage: 'Oakford',
		coordinates: '(24|-18)',
		tribe: 'teutons',
		hasHero: false,
		departureTime: '17:40',
		arrivalTime: '19:12',
		arrivalTimestamp: now + 1000 * 60 * 16,
		durationSeconds: 5520,
		elapsedSeconds: 4800,
		status: 'returning',
		distance: 8.9,
		troops: [{ troopName: 'Clubswinger', quantity: 80 }],
		resourcesCarried: { wood: 780, clay: 640, iron: 910, crop: 400 },
	},
	{
		id: 'mv7',
		group: 'hero',
		type: 'hero-adventure',
		sourceVillage: 'Northreach',
		destinationVillage: 'Unknown Adventure Site',
		coordinates: '(41|3)',
		tribe: 'teutons',
		hasHero: true,
		departureTime: '18:05',
		arrivalTime: '19:05',
		arrivalTimestamp: now + 1000 * 60 * 9,
		durationSeconds: 3600,
		elapsedSeconds: 3060,
		status: 'traveling',
		distance: 19.4,
		heroInfo: 'Solo adventure — medium difficulty.',
		troops: [],
	},
	{
		id: 'mv8',
		group: 'merchants',
		type: 'merchant-sent',
		sourceVillage: 'Northreach',
		destinationVillage: 'Millbrook',
		coordinates: '(31|4)',
		tribe: 'teutons',
		hasHero: false,
		departureTime: '18:30',
		arrivalTime: '19:02',
		arrivalTimestamp: now + 1000 * 60 * 6,
		durationSeconds: 1920,
		elapsedSeconds: 1600,
		status: 'traveling',
		distance: 9.7,
		resourcesCarried: { wood: 1200, clay: 900, iron: 600, crop: 300 },
		notes: 'Balancing crop reserves across villages.',
		troops: [],
	},
	{
		id: 'mv9',
		group: 'merchants',
		type: 'merchant-returning',
		sourceVillage: 'Ashford',
		destinationVillage: 'Northreach',
		coordinates: '(18|-27)',
		tribe: 'teutons',
		hasHero: false,
		departureTime: '17:55',
		arrivalTime: '19:15',
		arrivalTimestamp: now + 1000 * 60 * 19,
		durationSeconds: 4800,
		elapsedSeconds: 3900,
		status: 'returning',
		distance: 11.3,
		resourcesCarried: { wood: 0, clay: 0, iron: 0, crop: 0 },
		troops: [],
	},
]);

export function useMovementsData() {
	const groupCounts = computed<Record<MovementGroupKey, number>>(() => ({
		outgoing: movements.filter(m => m.group === 'outgoing').length,
		incoming: movements.filter(m => m.group === 'incoming').length,
		returning: movements.filter(m => m.group === 'returning').length,
		hero: movements.filter(m => m.group === 'hero').length,
		merchants: movements.filter(m => m.group === 'merchants').length,
	}));

	const byGroup = (group: MovementGroupKey) =>
		computed(() => movements.filter(m => m.group === group));

	return {
		movements,
		groupCounts,
		byGroup,
	};
}
